name: Build APK (with Docker)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Docker Buildozer
      run: |
        docker run --rm \
          -v "$PWD":/app \
          -w /app \
          kivy/buildozer \
          buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: photo-cleaner-apk
        path: bin/*.apk
