name: Build APK (No Docker)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          zip unzip git \
          python3-pip python3-setuptools python3-wheel \
          openjdk-17-jdk \
          build-essential ccache \
          libncurses5 libncurses5-dev \
          libstdc++6 \
          zlib1g zlib1g-dev \
          libffi-dev libssl-dev

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install cython
        pip install buildozer
        pip install Aidl

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: photo-cleaner-apk
        path: bin/*.apk
